[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@google/genai", "firebase-admin"]

[template.environment]
  GEMINI_API_KEY = "Your Google Generative AI key"
  VITE_CLERK_PUBLISHABLE_KEY = "Your Clerk publishable key"
  VITE_FIREBASE_API_KEY = "Your Firebase Web API Key"
  VITE_FIREBASE_AUTH_DOMAIN = "your-project.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "your-project-id"
  VITE_FIREBASE_STORAGE_BUCKET = "your-project.appspot.com"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "000000000000"
  VITE_FIREBASE_APP_ID = "1:000000000000:web:abc123"
  FIREBASE_SERVICE_ACCOUNT = "{\"project_id\":\"...\",\"client_email\":\"...\",\"private_key\":\"-----BEGIN PRIVATE KEY-----\\n...\\n-----END PRIVATE KEY-----\\n\"}"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
